@baseURL = http://localhost:8000/api
@adminToken = 37|ioxF0L9SxB1iNR3QuBMW80qYicBfS74kzOgjXhH13badf3d0
@profissionalToken = 32|WN6CcodAsaBS6l5KcYpNR3XggDxlxtJ2Na3kd0gw3283d954

# ------------------------------------------
# USUARIOS
# ------------------------------------------
# LOGIN
###
POST {{baseURL}}/usuarios/login
Content-Type: application/json

{
    "email": "admin@teste.com",
    "password": "123456"
}

# Logout
###
GET {{baseURL}}/usuarios/logout
Accept: application/json
Authorization: Bearer {{profissionalToken}}


# Perfil
###
GET {{baseURL}}/usuarios/perfil
Accept: application/json
Authorization: Bearer {{profissionalToken}}

# CADASTRAR
###
POST {{baseURL}}/usuarios
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "nome": "teste",
    "email": "teste3@gmail.com",
    "password": "123456",
    "admin": true,
    "nivel_id": 1
}

# BUSCAR USUÁRIOS
###
GET {{baseURL}}/usuarios
Accept: application/json
Authorization: Bearer {{adminToken}}

# BUSCAR UM USUARIO PELO ID
###
GET {{baseURL}}/usuarios/4
Accept: application/json
Authorization: Bearer {{adminToken}}

# ATUALIZAR USUARIO
###
PUT {{baseURL}}/usuarios/4
Accept: application/json
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "nome": "teste 123",
    "email": "teste@teste.com",
    "password": "123456",
    "admin": true,
    "nivel_id": 1
}

# REMOVE UM USUARIO
###
DELETE {{baseURL}}/usuarios/4
Accept: application/json
Authorization: Bearer {{adminToken}}

# SOLICITAR RECUPERAR SENHA
###
POST {{baseURL}}/usuarios/recuperar-senha
Accept: application/json
Content-Type: application/json

{
    "email": "carloswgama@gmail.com"
}

# ALTERAR SENHA
###
@tokenRecuperarSenha = eyJpdiI6Ik9ISUVvMG5HNmNScmo0R2NlQUlKSVE9PSIsInZhbHVlIjoiYldZVDRubkhhc2p2cEk0cmFNZnFvZz09IiwibWFjIjoiMDY3ZDIyMGE2MWU2Yzc5MDg4YzliYmI1NWRkMzEwMjY2OTkyZjBkY2MzYTM0NzFiZDJmYjExZTNiYWE0NzFiNCIsInRhZyI6IiJ9
PUT {{baseURL}}/usuarios/recuperar-senha/{{tokenRecuperarSenha}}
Accept: application/json
Content-Type: application/json

{
    "password": "123456"
}
