@baseURL = http://localhost:8000/api
@adminToken = 5|vywj9TIV1L8wzu4t2XVoPby9HFEC2Pk5YgPKDv8H1887e923
@profissionalToken = 6|fMya05whFuVyM9BTivpn9rS8cRifPgS1vJYCbWENe2d94828

# ------------------------------------------
# USUARIOS
# ------------------------------------------
# LOGIN
###
POST {{baseURL}}/usuarios/login
Content-Type: application/json

{
    "email": "profissional@teste.com",
    "password": "123456"
}


# Perfil
###
GET {{baseURL}}/usuarios/perfil
Accept: application/json
Authorization: Bearer {{adminToken}}

# CADASTRAR
###
POST {{baseURL}}/usuarios
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "nome": "teste",
    "email": "teste@teste.com",
    "password": "123456",
    "admin": true,
    "nivel_id": 1
}

# BUSCAR USUÁRIOS
###
GET {{baseURL}}/usuarios
Accept: application/json
Authorization: Bearer {{adminToken}}

# BUSCAR UM USUARIO PELO ID
###
GET {{baseURL}}/usuarios/4
Accept: application/json
Authorization: Bearer {{adminToken}}

# ATUALIZAR USUARIO
###
PUT {{baseURL}}/usuarios/4
Accept: application/json
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "nome": "teste 123",
    "email": "teste@teste.com",
    "password": "123456",
    "admin": true,
    "nivel_id": 1
}

# REMOVE UM USUARIO
###
DELETE {{baseURL}}/usuarios/4
Accept: application/json
Authorization: Bearer {{adminToken}}

